namespace: wordpress
app: wordpress
host: wordpress.local
wp:
  image:
    repository: wordpress
    tag: 6.6.2
  replicas: 1
  port: 80
  nodePort: 32000
  mountPath: /var/www/html

mysql:
  image:
    repository: mysql
    tag: 8.0
  port: 3306
  mountPath: /var/lib/mysql
  MYSQL_ROOT_PASSWORD: root-password321
  MYSQL_DATABASE: wordpress
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: my-secret-password321

persistence:
  size: 2Gi
