apiVersion: v1
entries:
  wordpress:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-10T21:50:30.19736308+04:00"
    description: A Helm chart for WP Deployment rs-school
    digest: 37eaca316562cfbc6715597b5a340f9dca9e7abd21752945669b8b5f5e8d01b9
    name: wordpress
    type: application
    urls:
    - https://SerPapanin.github.io/rsschool-wp-helm/wordpress-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-10T21:50:30.196666775+04:00"
