apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: wordpress-mysql
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        name: wordpress-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.MYSQL_ROOT_PASSWORD }}
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.MYSQL_DATABASE }}
        - name: MYSQL_USER
          value: {{ .Values.mysql.MYSQL_USER }}
        - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.MYSQL_PASSWORD }}
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: {{ .Values.mysql.mountPath }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
