apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
  annotations:
    # Required for Traefik Ingress Controller
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  selector:
  app: {{ .Values.app }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app }}
                port:
                  number: {{ .Values.wp.port }}
