apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
spec:
  ports:
    - port: {{ .Values.wp.port }}
      nodePort: {{ .Values.wp.nodePort }}
  selector:
    app: {{ .Values.app }}
  type: NodePort
