name: Deploy WP HELM chart

on:
  push:
    branches:
      #- master
      - task_5
  pull_request:
    branches:
      - master
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
  AWS_TF_STATE_FILE_NAME: ${{ vars.AWS_TF_STATE_FILE_NAME }}
  #TERRAFORM_GITHUB_ACTIONS_ROLE_NAME: ${{ vars.TERRAFORM_GITHUB_ACTIONS_ROLE_NAME }}
  TF_VERSION: ${{ vars.TF_VERSION }}
  TERRAFORM_DIR: ${{ vars.TERRAFORM_DIR }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TERRAFORM_DIR }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Get GitHub Runner IP
      id: runner_ip
      run: |
        echo "RUNNER_IP=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_ENV

    - name: Git checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHub-OIDC-TERRAFORM

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Initialize Terraform
      run: terraform init

    - name: Add Runner IP to Security Group
      env:
        RUNNER_IP: ${{ env.RUNNER_IP }}
        BASTION_SG_ID: ${{ env.BASTION_SG_ID }}
      run: |
        terraform apply -target=aws_security_group_rule.allow_runner_api -auto-approve -var="runner_ip=${RUNNER_IP}/32" -var="bastion_sg_id=${BASTION_SG_ID}"

    - name: Remove Runner IP from Security Group
      run: terraform destroy -target="aws_security_group_rule.allow_runner_api" -auto-approve
